# Generated by Django 5.2.11 on 2026-03-01 23:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trading', '0005_remove_customer_unique_mobile_per_business_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostProjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('st_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Standing Charge (p/day)')),
                ('consumption', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Consumption (kWh)')),
                ('flex_rate', models.DecimalField(decimal_places=8, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Flex Unit Rate (p/kWh)')),
                ('traded_price', models.DecimalField(decimal_places=8, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Traded Price (p/therm)')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Cost (£)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_projections', to='trading.customer')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'constraints': [models.UniqueConstraint(fields=('customer', 'year', 'month'), name='unique_projection_per_customer_month_year')],
            },
        ),
    ]
