# Generated by Django 4.2.20 on 2026-02-24 13:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_no', models.PositiveIntegerField(verbose_name='Trade Number')),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('p_therm', models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price per Thermal Unit')),
                ('percent', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('trade_date', models.DateField(verbose_name='Trade Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='trading.customer')),
            ],
            options={
                'ordering': ['-year', '-month', '-trade_no'],
            },
        ),
        migrations.AddConstraint(
            model_name='trade',
            constraint=models.UniqueConstraint(fields=('customer', 'year', 'month', 'trade_no'), name='unique_trade_per_customer_month_year'),
        ),
    ]
